import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
const origin='http://127.0.0.1:3001';const endpoint=origin+'/api/leads';
const data={name:'Teste automatizado',email:'qa@example.com',company:'',service:'web',message:'Teste de integração local do formulário.',consent:true,website:'',startedAt:Date.now()-5000,idempotencyKey:crypto.randomUUID()};
const ip='test-'+crypto.randomUUID();
const post=(body=data,headers={})=>fetch(endpoint,{method:'POST',headers:{Origin:origin,'Content-Type':'application/json','CF-Connecting-IP':ip,...headers},body:JSON.stringify(body)});
assert.equal((await fetch(endpoint)).status,405);
assert.equal((await post(data,{Origin:'https://invalid.example'})).status,403);
assert.equal((await post({...data,consent:false})).status,400);
assert.equal((await post({...data,email:'invalid'})).status,400);
assert.equal((await post({...data,website:'spam'})).status,400);
assert.equal((await post({...data,message:'x'.repeat(20000)})).status,400);
assert.equal((await post()).status,201);
assert.equal((await post()).status,201);
const db=new DatabaseSync('.sites-runtime/preview.sqlite');
assert.equal(db.prepare('SELECT count(*) AS n FROM leads WHERE id = ?').get(data.idempotencyKey).n,1);
for(let i=0;i<3;i++)assert.equal((await post()).status,201);
assert.equal((await post()).status,429);
const page=await fetch(origin);assert.equal(page.status,200);assert.ok(!page.headers.get('Content-Security-Policy').includes("script-src 'self' 'unsafe-inline'"));
console.log('PASS: persistence, idempotency, origin, validation, consent, honeypot, body limit, rate limit and CSP.');
